name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout test repo (auto-test-cicd)
        uses: actions/checkout@v4
        with:
          repository: Mutto1003/auto-test-cicd
          path: test-repo

      - name: Run tests
        run: |
          cd test-repo
          npm install
          npm run test         # หรือคำสั่งที่เหมาะสมกับ repo ของคุณ

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: demo-app
          path: '.'  # หรือ '.' หาก index.html อยู่ root
          retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: index